######################################################################
# Automatically generated by qmake (3.0) ma joulu 30 22:49:08 2013
######################################################################

TEMPLATE = app
TARGET = qtsrc
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += AtisWidget.h  MainWindow.h levelmenu.h PeliView.h AtisWidget.h Metar.hpp apuvalineet.hpp AtisController.hpp PeliWidget.h
SOURCES += qtmain.cpp apuvalineet.cpp AtisController.cpp
