######################################################################
# Automatically generated by qmake (3.0) ma joulu 30 22:49:08 2013
######################################################################

TEMPLATE = app
TARGET = qtsrc
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += AtisView.h levelmenu.h MainWindow.h PeliWidget.h
SOURCES += qtmain.cpp
