######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 29 19:33:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
HEADERS += levelmenu.h

# Input
SOURCES += qtmain.cpp
